$(function(){var uploadObj={maxUpload:maxUploadCounts,uploadInfo:{},uploadQueue:[],previewQueue:[],isBusy:false,isUploading:null,getgps:1,xhr:{},countUpload:function(){var num=0;$.each(uploadObj.uploadInfo,function(i,n){if(n){++num;}});return num;},checkIsUploading:function(){uploadObj.isUploading=setInterval(function(){setTimeout(function(){if(uploadObj.previewQueue.length){var jobId=uploadObj.previewQueue.shift();uploadObj.uploadPreview(jobId);}},1);setTimeout(function(){if(!uploadObj.isBusy&&uploadObj.uploadQueue.length){var jobId=uploadObj.uploadQueue.shift();uploadObj.isBusy=true;uploadObj.createUpload(jobId);}},10);},300);},clearIsUploading:function(){clearInterval(uploadObj.isUploading);},delUploadPicsById:function(id){var picsId=$('#pics_li_'+id).attr('data-rel');var coverId=$('#pic_url').attr('data-rel');if(picsId){$.post(delUploadUrl,{"id":picsId,"__hash__":hash});$('#pics_list_'+picsId).remove();if(coverId==picsId){$('#pic_url').val('').attr('data-rel','');}}
$('#pics_li_'+id).remove();},uploadPreview:function(id){var reader=new FileReader();var uploadBase64;var conf={},file=uploadObj.uploadInfo[id].file;if(window.NETTYPE==window.NETTYPE_WIFI){conf={maxW:720,maxH:1000,quality:0.8,};}else{conf={maxW:640,maxH:1000,quality:0.8,};}
reader.onload=function(e){var result=this.result;if(file.type=='image/jpeg'){try{var jpg=new JpegMeta.JpegFile(result,file.name);}catch(e){$.DIC.dialog({content:'图片不是正确的图片数据',autoClose:true});$('#pics_li_'+id).remove();return false;}
if(jpg.tiff&&jpg.tiff.Orientation){conf=$.extend(conf,{orien:jpg.tiff.Orientation.value});}}
if(ImageCompresser.support()){var img=new Image();img.onload=function(){try{uploadBase64=ImageCompresser.getImageBase64(this,conf);}catch(e){$.DIC.dialog({content:'压缩图片失败',autoClose:true});$('#pics_li_'+id).remove();return false;}
if(uploadBase64.indexOf('data:image')<0){$.DIC.dialog({content:'上传照片格式不支持',autoClose:true});$('#pics_li_'+id).remove();return false;}
uploadObj.uploadInfo[id].file=uploadBase64;$('#pics_li_'+id).find('img').attr('src',uploadBase64);uploadObj.uploadQueue.push(id);}
img.onerror=function(){$.DIC.dialog({content:'解析图片数据失败',autoClose:true});$('#pics_li_'+id).remove();return false;}
img.src=ImageCompresser.getFileObjectURL(file);}else{uploadBase64=result;if(uploadBase64.indexOf('data:image')<0){$.DIC.dialog({content:'上传照片格式不支持',autoClose:true});$('#pics_li_'+id).remove();return false;}
uploadObj.uploadInfo[id].file=uploadBase64;$('#pics_li_'+id).find('img').attr('src',uploadBase64);uploadObj.uploadQueue.push(id);}}
reader.readAsBinaryString(uploadObj.uploadInfo[id].file);},createUpload:function(id){if(!uploadObj.uploadInfo[id]){return false;}
var progressHtml='<div class="progress" id="progress'+id+'"><div class="proBar" style="width:0%;"></div></div>';$('#pics_li_'+id).find('.maskLay').after(progressHtml);var progress=function(e){if(e.target.response){var result=$.parseJSON(e.target.response);if(result.status!=1){$.DIC.dialog({content:'网络不稳定，请稍后重新操作',autoClose:true});removePic(id);}}
var progress=$('#progress'+id).find('.proBar');if(e.total==e.loaded){var percent=100;}else{var percent=100*(e.loaded/e.total);}
if(percent>100){percent=100;}
progress.css('width',percent+'%');if(percent==100){$('#pics_li_'+id).find('.maskLay').remove();$('#pics_li_'+id).find('.progress').remove();}}
var removePic=function(id){donePic(id);$('#pics_li_'+id).remove();}
var donePic=function(id){uploadObj.isBusy=false;if(typeof uploadObj.uploadInfo[id]!='undefined'){uploadObj.uploadInfo[id].isDone=true;}
if(typeof uploadObj.xhr[id]!='undefined'){uploadObj.xhr[id]=null;}}
var complete=function(e){var progress=$('#progress'+id).find('.proBar');progress.css('width','100%');$('#pics_li_'+id).find('.maskLay').remove();$('#pics_li_'+id).find('.progress').remove();donePic(id);var result=$.parseJSON(e.target.response);if(result.status==1){var input='<input type="hidden" id="pics_list_'+result.data.id+'" name="pics_list[]" value="'+result.data.id+'">';$('#pics_li_'+id).attr('data-rel',result.data.id);$('#pics_li_'+id).attr('data-url',result.data.furl);$('#add-feedback').append(input);}else{$.DIC.dialog({content:'网络不稳定，请稍后重新操作',autoClose:true});removePic(id);}}
var failed=function(){$.DIC.dialog({content:'网络断开，请稍后重新操作',autoClose:true});removePic(id)}
var abort=function(){$.DIC.dialog({content:'上传已取消',autoClose:true});removePic(id)}
var formData=new FormData();formData.append('pic',uploadObj.uploadInfo[id].file);formData.append('__hash__',hash);uploadObj.xhr[id]=new XMLHttpRequest();uploadObj.xhr[id].addEventListener("progress",progress,false);uploadObj.xhr[id].addEventListener("load",complete,false);uploadObj.xhr[id].addEventListener("abort",abort,false);uploadObj.xhr[id].addEventListener("error",failed,false);uploadObj.xhr[id].open("POST",uploadUrl+'&t='+Date.now());uploadObj.xhr[id].send(formData);},checkUploadBySysVer:function(){if(jQuery.os.android&&(jQuery.os.version.toString().indexOf('4.4')===0||jQuery.os.version.toString()<='2.1')){$.DIC.dialog({'content':'您的手机系统暂不支持传图','autoClose':true});return false;}else if(jQuery.os.ios&&jQuery.os.version.toString()<'6.0'){$.DIC.dialog({'content':'手机系统不支持传图，请升级到ios6.0以上','autoClose':true});return false;}
if(jQuery.os.wx&&jQuery.os.wxVersion.toString()<'5.2'){$.DIC.dialog({'content':'当前微信版本不支持传图，请升级到最新版','autoClose':true});return false;}
return true;},checkForm:function(){$.each(uploadObj.uploadInfo,function(i,n){if(n&&!n.isDone){$.DIC.dialog({content:'图片上传中，请等待',autoClose:true});return false;}});var contentLen=$.DIC.mb_strlen($.DIC.trim($('#content').val()));if(contentLen<5){$.DIC.dialog({content:'留言内容不能少于5个字符',autoClose:true});return false;}
return true;},checkPicSize:function(file){if(file.size>10000000){return false;}
return true;},checkPicType:function(file){return true;},initUpload:function(){$('#addPic').on('click',function(){uploadObj.checkUploadBySysVer();});$('#adduploadField').on('click',function(){if(uploadObj.isBusy){$.DIC.dialog({content:'上传中，请稍后添加',autoClose:true});return false;}});$('body').on('change','#adduploadField',function(e){e=e||window.event;var fileList=e.target.files;if(!fileList.length){return false;}
for(var i=0;i<fileList.length;i++){if(uploadObj.countUpload()>=uploadObj.maxUpload){$.DIC.dialog({content:'你最多只能上传'+uploadObj.maxUpload+'张照片',autoClose:true});break;}
var file=fileList[i];if(!uploadObj.checkPicSize(file)){$.DIC.dialog({content:'图片体积过大',autoClose:true});continue;}
if(!uploadObj.checkPicType(file)){$.DIC.dialog({content:'上传照片格式不支持',autoClose:true});continue;}
var id=Date.now()+i;uploadObj.uploadInfo[id]={file:file,isDone:false,};var html='<li id="pics_li_'+id+'" data-rel="0"><div class="photoCut"><img src="'+defaultImgUrl+'" class="attchImg"></div>'+'<div class="maskLay"></div>'+'<a href="javascript:;" class="cBtn spr db " title="" _id="'+id+'">关闭</a></li>';$('#addPic').before(html);uploadObj.previewQueue.push(id);if(!uploadObj.isUploading){uploadObj.checkIsUploading();}}
if(uploadObj.countUpload()>=uploadObj.maxUpload){$('#addPic').hide();}
$(this).val('');});$('.photoList').on('click','.cBtn',function(){var id=$(this).attr('_id');if(uploadObj.xhr[id]){uploadObj.xhr[id].abort();}
uploadObj.delUploadPicsById(id);uploadObj.uploadInfo[id]=null;if(uploadObj.countUpload()<uploadObj.maxUpload){$('#addPic').show();}});$(".locationCon").on('click',function(){if(uploadObj.getgps==1||uploadObj.getgps==2){uploadObj.getgps=0;$('.locationCon').removeClass('curOn').html('<i class="locInco commF">'+'所有城市');$('#LBSInfoLatitude').val('');$('#LBSInfoLongitude').val('');$('#LBSInfoProvince').val('');$('#LBSInfoCity').val('');$('#LBSInfoDistrict').val('');$('#LBSInfoStreet').val('');$('#cityCode').val('');}else if(uploadObj.getgps==0){uploadObj.getgps=1;$('.locationCon').html('<i class="locInco commF">'+'正在定位...');getGpsInfo.init();}});}};getGpsInfo.init();uploadObj.initUpload();smileyObj.init();$(".expreSelect").on("click",function(){if($('.expreList').css('display')!='none'){smileyObj.hide();}else{smileyObj.show();}});$(".photoSelect").on("click",smileyObj.hide);timer=setInterval(function(){$.DIC.strLenCalc($('textarea[name="content"]')[0],'pText',1000);if(mystorage.support){mystorage.set('title',$("#title").val());mystorage.set('content',$('#content').val());}},800);var isSubmitButtonClicked=false;$('#submitButton').on('click',function(){if(isSubmitButtonClicked||!uploadObj.checkForm()){return false;}
var opt={success:function(re){if(re.status==1){}else{isSubmitButtonClicked=false;}},error:function(re){isSubmitButtonClicked=false;}};isSubmitButtonClicked=true;$.DIC.showLoading('block','正在保存...');$.post(forumPostUrl,$("#add-feedback").serialize(),function(result){$.DIC.showLoading('hide');if(result.status==1){if(mystorage.support){mystorage.clear();}
$.DIC.dialog({content:'留言成功，感谢您的反馈！',autoClose:false});setTimeout(function(){document.location=jumpToUrl+'&fid='+result.data;},2000);}else{isSubmitButtonClicked=false;$.DIC.dialog({content:result.info,autoClose:true});}},'json').error(function(){isSubmitButtonClicked=false;$.DIC.showLoading('hide');$.DIC.dialog({content:'留言发布失败',autoClose:true});});return false;});$('.cancelBtn').on('click',function(){if($('.photoList .attchImg').length>0){$.DIC.dialog({content:'是否放弃当前内容?<br/><span style="font-size:12px">上传的图片将丢失</span>',okValue:'确定',cancelValue:'取消',isMask:true,ok:function(){history.go(-1);}});}else{history.go(-1);}
return false;});$('#content').on('focus',function(){$('.bNav').hide();}).on('blur',function(){$('.bNav').show();});$("#mqOption").click(function(){$("#fwin_mask_sideBar").show();$("#fwin_dialog_sideBar").show();});$("#fwin_mask_sideBar").click(function(){$("#fwin_mask_sideBar").hide();$("#fwin_dialog_sideBar").hide();});if(mystorage.support){var title=mystorage.get('title');var content=mystorage.get('content');if(title){$("#title").val(title);}
if(content){$("#content").val(content)}}});