$(function(){libScroll.initScroll({ulSelector:'.slideBox ul',isFlip:false,cSelector:'.container'});if(pages>1){$("#loadNext").show();$("#showAll").hide();}else{$("#loadNext").hide();$("#showAll").show();}
smileyObj.init();$(".expreSelect").live("click",function(){if($('.expreList').css('display')!='none'){smileyObj.hide();}else{smileyObj.show();}});$(".photoSelect").on("click",smileyObj.hide);var timer=setInterval(function(){$.DIC.strLenCalc($('#content')[0],'pText',280);},500);$(".viewBtn").live('click',function(e){var thisObj=$(this);var text=thisObj.html();var height='',returnTop=false;if(text=='收起'){returnTop=true;height='150px';text='全文';}else{height='none';text='收起';}
thisObj.parent().find('p').css('max-height',height);thisObj.html(text);if(returnTop){scroll(0,thisObj.closest('.topicBox').position().top);}});$("#mqOption").click(function(){$("#fwin_mask_sideBar").show();$("#fwin_dialog_sideBar").show();});$("#fwin_mask_sideBar").click(function(){$("#fwin_mask_sideBar").hide();$("#fwin_dialog_sideBar").hide();});var isLoading=false;$(window).scroll(function(){if(nowPage<pages){totalheight=parseFloat($(window).height())+parseFloat($(window).scrollTop());if($(document).height()<=totalheight){if(isLoading==false){isLoading=true;nowPage+=1;if(nowPage>=pages){$("#loadNext").hide();$("#showAll").show();}
$.post(loadMoreDataUrl,{"is_ajax":1,"vid":vid,"tid":tid,"p":nowPage},function(result){if(result.status==1){$("#mainContentList").append(result.data.items);showBigPicsList();}else{$.DIC.dialog({content:'数据加载失败',autoClose:true});}
isLoading=false;},"json");}}}});$('.like').live('click',function(){var $this=$(this);var i_obj=$this.find('i');var num=parseInt($this.text());var html="";if(i_obj.hasClass("noPraise")){html="<i class='praise'></i>";num++;$.post(praiseUrl,{"fid":$this.attr("fid")});}else{html="<i class='noPraise'></i>";num--;$.post(delPraiseUrl,{"fid":$this.attr("fid")});}
$this.html(html+num);return false;});$("#searchShow").click(function(){$("#searchBox").show().animate({width:'100%'},"100");$("#search").focus();});$("#searchBox .close").click(function(){var s_box=$("#searchBox");s_box.animate({width:'0'},"100",function(){s_box.hide();$("#search").val("");});});$("#searchBtn").click(function(){var sear=$("#search");var s_text=$.DIC.trim(sear.val());if(!s_text){$.DIC.dialog({content:'请输入关键字',autoClose:true});return false;}
document.location=searchUrl+'&q='+s_text;});$('.PerPopBtn').live('click',function(){var _obj=$(this).parents('.personImgDate').find('.perHandle');if(_obj.css('display')=='none'){_obj.show();}else{_obj.hide();}
return false;});$('.perType').live('click',function(){var $this=$(this);var fid=$this.parent().attr('fid');var type=$this.data('type');var cont="";if(type=="delete"){cont="确定要删除吗？";}else if(type=="top"){cont="确定要置顶？";}else if(type=="down"){cont="确定要下沉？";}else if(type=="report"){cont="确定要举报？";}
$.DIC.dialog({content:cont,okValue:'确定',cancelValue:'取消',isMask:true,ok:function(){$.post(actionUrl,{"fid":fid,"act":type},function(result){if(!result.status){$.DIC.dialog({content:result.info,autoClose:true});}else if(type=="delete"){$("#forum-"+fid).fadeOut();}else{$.DIC.dialog({content:'操作成功',autoClose:true});}},'json');},cancel:function(){$this.parent().parent().find('.PerPopBtn').click();}});return false;});$("#sendCancel").live('click',function(){toggleReplyBox('close');$('#replyForm')[0].reset();smileyObj.hide();return false;});$("#sendBtn").live('click',function(){var fid=$("#replyForm input[name=fid]").val();var fuid=$("#replyForm input[name=fuid]").val();var parent_id=$("#replyForm input[name=parent_id]").val();var cont=$.trim($("#content").val());if(cont.length<1){$.DIC.dialog({content:'回复内容太短！',autoClose:true});return;}
if(cont.length>140){$.DIC.dialog({content:'回复内容太长！',autoClose:true});return;}
$.DIC.showLoading('block','正在保存...');$.post(postUrl,$("#replyForm").serialize(),function(result){$.DIC.showLoading('hide');if(result.status==1){var html="";var className=result.data.is_private?'class="private"':'';if(fuid!=""&&fuid!=null){html="<li uid='"+UserId+"' pid='"+result.data.pid+"' fid='"+fid+"' author='"+User+"' "+className+"><a href='javascript:;' class='sW fl'><span>"+User+"</span></a><span class='fl'>&nbsp;回复&nbsp;</span><a href='javascript:;' class='sW fl'><span>"+Author+"：</span></a>"+result.data.cont+"</li>";}else{html="<li uid='"+UserId+"' pid='"+result.data.pid+"' fid='"+fid+"' author='"+User+"' "+className+"><a href='javascript:;' class='sW fl'><span>"+User+"：</span></a>"+result.data.cont+"</li>";}
$("#topicList_show_"+fid).show();$("#forum-"+fid+" .replylist").append(html);toggleReplyBox('close');$('#replyForm')[0].reset();smileyObj.hide();var replys=parseInt($("#post-count-"+fid).text());$("#post-count-"+fid).text((replys+1));}else{$.DIC.dialog({content:result.info,autoClose:true});}},'json');return false;});$(".replylist li").live('click',function(){var $this=$(this);var fid=$this.attr('fid');var fuid=$this.attr('uid');var author=$this.attr('author');var pid=$this.attr('pid');if(fuid==UserId){$.DIC.dialog({content:"确定删除回复？",okValue:'确定',cancelValue:'取消',isMask:true,ok:function(){$this.fadeOut();$.post(delPostUrl,{"pid":pid,"fid":fid},function(result){if(result.status==1){var replys=parseInt($("#post-count-"+fid).text());$("#post-count-"+fid).text((replys-1));}else{$.DIC.dialog({content:result.info,autoClose:true});}},'json');return;},cancel:function(){}});}else{Author=author;toggleReplyBox('open');$("#content").attr('placeholder','@'+author);$("#replyForm input[name=fid]").val(fid);$("#replyForm input[name=fuid]").val(fuid);$("#replyForm input[name=parent_id]").val(pid);}
return false;});$(".threadReply").live('click',function(){toggleReplyBox('open');var $this=$(this);var fid=$this.attr('fid');$("#replyForm input[name=fid]").val(fid);$("#replyForm input[name=fuid]").val('');$("#replyForm input[name=parent_id]").val('');});$(".show-more").live('click',function(){document.location=$(this).attr('data-href');});function showBigPicsList(){$(".pictureList").find("img").unbind("click").click(function(){var urls=[];var $this=$(this);var parent=$this.parents(".pictureList");var current=parseInt($this.attr('data-current'));parent.find('img').each(function(i,evt){urls.push($(this).attr('data-rel'));});try{WeixinJSBridge.invoke('imagePreview',{current:urls[current],urls:urls});}catch(e){}}).lazyload({effect:"fadeIn"});};showBigPicsList();function toggleReplyBox(type){var b_box=$("#fwin_mask_replyForm");var r_box=$("#fwin_dialog_replyForm");if(type=="open"){b_box.show();r_box.show();}else if(type=="close"){b_box.hide();r_box.hide();}}
$.getJSON(getAdvsUrl,{"id":advsId},function(res){if (res.status==1){$("#pEvent").html(res.data);}});
});