$(function(){if(isNewUser){Msg.setText('我知道了');Msg.alert('hi~欢迎使用签到功能，请在下面选择你喜欢的树苗进行播种，并记得每天给它浇水，连续7天浇水会获得惊喜，如果你中途忘记浇水，小树苗会立即枯死的哦！','新手教程');}
if(isHarvest){$("#harvest").fadeIn(1000);}
$("#sign-in").click(function(){if(!isBind){Msg.alert('你还没有入住小区呢，请先入住小区','入住小区',function(){document.location=userBindUrl;return false;});}
if(isSignin){showTips('你已经签到了，明天再来');return false;}
if(isHarvest){showTips('请先收割');return false;}
if(!TreeId||isEmpty){showTips('请在下面选择你喜欢的树苗');return false;}
if(!isWater){showTips('正在处理...');$.getJSON(saveUrl,{},function(res){showTips('');if(res.status==1){isWater=true;var _kettle=$('#kettle'),_water=$("#water");_kettle.css({'transform':'rotate(-45deg)','transition':'500ms linear'});window.setTimeout(function(){_water.show().animate({height:'300px'},1000,"linear",function(){if(Day<7){var tree=$("#tree");Day++;dataForWeixin.desc="我已经连续签到"+Day+"次了，iphone6有木有？";tree.removeClass().addClass('tree-'+Day).attr('src',ImgUrl+treeArry[Day-1]);$.tipsBox({obj:tree,str:'+'+res.data.credits});$("#sign-day").text(res.data.signinTimes+' 天');$("#leave-day").text(7-Day);if(Day==7)$("#harvest").fadeIn(1000);$("#my-score").html(res.data.score);isSignin=true;}
_water.animate({height:'0'},500,"linear",function(){isWater=false;});_kettle.css({'transform':'rotate(0deg)','transition':'500ms linear'});});},500);}else{showTips(res.info);}});}});$("#plant-box").click(function(){var _tree=$("#tree");if(Day==7){showTips('正在处理...');$.getJSON(harvestUrl,{},function(res){showTips('');if(res.status==1){var bigTree=$("#big-tree-num"),bt_num=parseInt(bigTree.text());_tree.attr('src',ImgUrl+'no.png');$("#harvest").fadeOut(100);bigTree.text(bt_num+1);Day=0;isEmpty=true;treeArry=[];TreeId=0;isHarvest=false;showTips('收割成功啦，继续努力哟！');}else{showTips(res.info);}});}});$("#change-score").click(function(){var bigTree=$("#big-tree-num")
bigTreeNum=bigTree.text();if(bigTreeNum<=0){showTips('没有成树可兑换！');return false;}else{showTips('正在处理...');$.getJSON(exchangeUrl,{},function(res){showTips('');if(res.status==1){showTips('兑换成功！积分+'+res.data.credit);bigTree.text(res.data.has)}else{showTips(res.info);}});}});$('#tree-list').find('li:not(:last)').click(function(){if(TreeId){showTips('你的树苗还在成长，请成熟后再种新树苗');return false;}
var _this=$(this).find(".plant"),sapling=null;TreeId=_this.data('tree');sapling=$('#small-tree-'+TreeId);var sapling_num=parseInt(sapling.text());if(sapling_num<=0){showTips('树苗不够！');return false;}
showTips('正在处理...');$.getJSON(setplantUrl,{"plant_id":TreeId},function(res){showTips('');if(res.status==1){$('#container').removeClass().addClass('bg-'+TreeId);setTreeArry(TreeId);showTips('种植成功，快来浇水吧！');sapling.text(sapling_num-1);isEmpty=false;}else{showTips(res.info);}});});function setTreeArry(id){if(id){treeArry=[];for(var i=0;i<7;i++){if(i==0){treeArry.push('s-1-1.png');}else{treeArry.push('s-'+id+'-'+(i+1)+'.png');}}
loadImgUrl=ImgUrl+treeArry[Day];var img=new Image();img.src=loadImgUrl;}}
function initPage(){var w_width=$(window).width();var w_height=$(window).height();var b_height=$(document.body).height();if(b_height>w_height){$("#container").height(b_height);}else{$("#container").height(w_height);}}
function showTips(txt,time){var htmlCon='';if(txt!=''){htmlCon='<div id="tip-box" class="tipsBox"></div>';if(!hasTipBox){$('body').prepend(htmlCon);hasTipBox=true;}
$("#tip-box").show().html(txt);time=time||1500;setTimeout(function(){$('#tip-box').hide();},time);}else{$('#tip-box').hide();}}
$(window).resize(function(){initPage();});$(window).load(function(){setTreeArry(TreeId);initPage();});});;(function($){$.extend({tipsBox:function(options){options=$.extend({obj:null,str:"+1",startSize:"20px",endSize:"30px",interval:1200,color:"red",callback:function(){}},options);$("body").append("<span class='num'>"+options.str+"</span>");var box=$(".num");var left=options.obj.offset().left+options.obj.width()/2;var top=options.obj.offset().top;box.css({"position":"absolute","left":left+"px","top":top+"px","z-index":9999,"font-size":options.startSize,"line-height":options.endSize,"color":options.color});box.animate({"font-size":options.endSize,"opacity":"1","top":top-parseInt(options.endSize)+"px"},options.interval,function(){box.remove();options.callback();});}});})(jQuery);