var Timer,LeftTimer,AllTimer;var _config={grid:gameGrid,countTime:gameCountTime,gameTime:gameTime,tips:1,hard:gameHard,score:gameScore};var MyStorage=storage('BigBrain');var ArryNum=[],SortNum=[];var ClickIndex=0,IsClick=false,AllScore=0,Level=0,GameName=null,Defeat='50',shareData={"imgUrl":gameShareImg,"timeLineLink":gameShareUrl,"tTitle":"我发现一个非常好玩的游戏“最强大脑”，你敢来挑战吗？","tContent":"测一测你的大脑发育不良还是天才记忆！","callBack":function(){}};function init(){var c_width=$("#container").width();$("#box").css({width:c_width+'px',height:c_width+'px'});var grid=_config.grid*_config.grid;var html="";var i=0;for(i=0;i<grid;i++){html+="<span class='item'></span>";}
$("#box").html(html);}
function next(){if(Level>=_config.hard){_config.tips=0;}else{_config.tips=1;}
getData();}
function getData(){$("#load-data").show();ArryNum=[],SortNum=[];$.ajax({type:'GET',url:gameDataUrl,data:{"level":(Level+1)},dataType:'json',cache:false,timeout:5000,success:function(json){ArryNum=json.data.list;SortNum=json.data.sort;if(ArryNum){$("#load-data").hide();openALlcard();ClickIndex=0;window.clearInterval(Timer);var time=_config.countTime;$("#c_time").show();$("#l_time").hide();$("#count-down").text(time);Timer=window.setInterval(function(){$("#count-down").text(time);if(time==0){closeALlcard();window.clearInterval(Timer);}
time--;},1000);$("#level-box").text(AllScore);}},error:function(XMLHttpRequest,textStatus,errorThrown){getData();}});}
function openLeftcard(){window.clearInterval(LeftTimer);$("#box span").each(function(index){var _this=$(this);if(_this.hasClass('clicked')){return;}
_this.text('');_this.css({'background':'#d3d3d3'}).html('<em>'+ArryNum[index]+'</em>');});IsClick=false;}
function openALlcard(){window.clearInterval(LeftTimer);$("#box span").each(function(index){var _this=$(this);_this.css({'background':'#d3d3d3'}).html('<em>'+ArryNum[index]+'</em>');});IsClick=false;}
function closeALlcard(){$("#box span").each(function(index){var _this=$(this);if(_this.hasClass('clicked')){_this.removeClass('clicked');}
if(_config.tips&&ArryNum[index]){_this.css({'background':'#fccf33'}).html('<em>?</em>');}else{_this.css({'background':'#fccf33'}).html('');}});IsClick=true;window.clearInterval(LeftTimer);var gameTime=_config.gameTime;$("#c_time").hide();$("#l_time").show();$("#left-time").text(gameTime);LeftTimer=window.setInterval(function(){gameTime--;$("#left-time").text(gameTime);if(gameTime==0){openALlcard();window.setTimeout(function(){gameOver();},500);}},1000);}
function gameOver(){var name="你的大脑发育不全";GameName='获得“大脑发育不全”称号';if(Level>0){$.post(gameSaveUrl,{"game":gameId,"score":AllScore,"level":Level,"__hash__":hash},function(res){if(res.status){Defeat=res.data.win;if(Defeat<=30){name="你的"+res.data.title;GameName='获得“'+res.data.title+'”称号';}else{name=GameName='获得“'+res.data.title+'”称号';}
shareGame();if(!isLogin){$(".bind-box").show();return false;}else{$("#game-name").text("累计获得"+AllScore+"个游戏币，击败全国"+Defeat+"%业主，"+name+"！");$(".restart-box").fadeIn(100);}
MyStorage.set('level','');MyStorage.set('score','');}else{showTips(res.info);}},'json');}else{shareGame();$("#game-name").text("累计获得"+AllScore+"个游戏币，击败全国0%业主，"+name+"！");$(".restart-box").fadeIn(100);}}
function showTips(txt,time,status){var htmlCon='';if(txt!=''){if(status!=0&&status!=undefined){htmlCon='<div class="tipsBox" style="width:120px; overflow:hidden; position:fixed; left:50%; margin-left:-60px; top:50%; text-align:center; color:#FFF; padding:5px 15px; font-size:12px; background:rgba(0,0,0,.8); box-shadow:0 0 5px rgba(0,0,0,.8); z-index:100;">'+txt+'</div>';}else{htmlCon='<div class="tipsBox" style="width:120px; overflow:hidden; position:fixed; left:50%; margin-left:-60px; top:50%; text-align:center; color:#FFF; padding:5px 15px; font-size:12px; background:rgba(0,0,0,.8); box-shadow:0 0 5px rgba(0,0,0,.8); z-index:100;">'+txt+'</div>';}
$('body').prepend(htmlCon);if(time==''||time==undefined){time=1500;}
setTimeout(function(){$('.tipsBox').remove();},time);}}
$(function(){var onClick="ontouchstart"in document.documentElement?"touchstart":"click";$("#box").on(onClick,'span',function(){if(IsClick){var _this=$(this);var index=_this.index();if(_this.hasClass('clicked')){return;}
if(index==SortNum[ClickIndex]){_this.css({'background':'#999'}).html('<em>'+ArryNum[index]+'</em>').addClass("clicked");ClickIndex++;if(SortNum.length==ClickIndex){IsClick=false;openLeftcard();Level++;window.setTimeout(function(){$("#next-level").click();},500);AllScore+=ClickIndex*_config.score;MyStorage.set('level',Level);MyStorage.set('score',AllScore);}}else{IsClick=false;openLeftcard();window.setTimeout(function(){gameOver();},500);}}});$(window).load(function(){$("#status").fadeOut();$("#loading").delay(350).fadeOut("slow");init();});$("#next-level").click(function(){$(this).hide();next();});$('.start-game').click(function(){Level=0,AllScore=0;if(MyStorage.support){var level_last=MyStorage.get('level');var score_last=MyStorage.get('score');if(level_last){Level=parseInt(level_last);AllScore=parseInt(score_last);}}
$(".alert-box").hide();next();});$(".share").click(function(){$("#share-box").fadeIn(200);});$("#share-box").click(function(){$("#share-box").fadeOut(200);});});function shareGame(){shareData={"imgUrl":gameShareImg,"timeLineLink":gameShareUrl,"tTitle":"我在最强大脑测试中击败全国"+Defeat+"%业主，"+GameName+"，你敢来挑战？","tContent":"我获得"+AllScore+"个游戏币，"+GameName+" 有木有超越的！","callBack":function(){}}}
document.addEventListener('WeixinJSBridgeReady',function onBridgeReady(){WeixinJSBridge.call('hideToolbar');WeixinJSBridge.on('menu:share:appmessage',function(argv){WeixinJSBridge.invoke('sendAppMessage',{"img_url":shareData.imgUrl,"img_width":"640","img_height":"640","link":shareData.timeLineLink,"desc":shareData.tContent,"title":shareData.tTitle},function(res){(shareData.callback)();});});WeixinJSBridge.on('menu:share:timeline',function(argv){WeixinJSBridge.invoke('shareTimeline',{"img_url":shareData.imgUrl,"img_width":"640","img_height":"640","link":shareData.timeLineLink,"desc":shareData.tContent,"title":shareData.tTitle},function(res){(shareData.callback)();});});},false);