H=960;function qp_a(b){}
var qp_b=30,qp_c,qp_d=5,qp_e=3,qp_f=qp_e,qp_g=420,qp_h=0,qp_i=[],qp_j=20,qp_k=0,qp_l,qp_m=0,qp_n=0,qp_o=0,m_arry=['1000','500','100'],m_num=m_arry[1];function qp_p(){JielinStage.stage.arrow.visible=!0;qp_q=jielinApp.score=0;qp_n=qp_b;qp_m=-1;JielinStage.stage.num.txt.text=qp_n+'"';qp_k=0;qp_o=1;jielinApp.onGameStarted()}
function qp_r(){JielinStage.stage.splash.visible=!0}
function qp_s(){JielinStage.stage.arrow.visible=!1;qp_m=0}
function qp_t(){qp_o=3;qp_l=setTimeout(function(){window.clearTimeout(qp_l)},900);qp_u();jielinApp.onNewScore(jielinApp.score);jielinApp.onGameOver();JielinStage.stage.gameover.visible=!0;JielinStage.stage.gameover.refresh()}
function qp_v(b){IS_ANDROID&&(createjs.Sound.registMySound("count",0),createjs.Sound.registMySound("silenttail",0.25));qp_w();qp_u()}
function Qp_x(){this.initialize();this.bg=new createjs.Shape;this.bg.graphics.beginFill("#559966").drawRect(0,0,W,H);this.addChild(this.bg);this.label=new createjs.Bitmap(JielinStage.queue.getResult("splashtitle"));this.label.x=(W-this.label.getBounds().width)/2;this.label.y=100;this.addChild(this.label);this.start=new createjs.Bitmap(JielinStage.queue.getResult("mb0"));this.start.y=H-300;this.start.x=(W-this.start.getBounds().width)/2;this.addChild(this.start);this.arrow=new createjs.Bitmap(JielinStage.queue.getResult("starttip"));this.arrow.y=H-400;this.arrow.x=(W-this.arrow.getBounds().width)/2;this.addChild(this.arrow);var d,c;this.start.on("mousedown",function(a){0==qp_o&&(d=a.localY,c=H-300)});this.start.on("pressmove",function(a){0==qp_o&&SplashPressmoveEvent(a.localY-d,c)});this.start.on("pressup",function(a){0==qp_o&&30>d-a.localY&&(createjs.Sound.play("count",!0),createjs.Tween.get(JielinStage.stage.splash.start).to({y:-H},400).call(function(b){JielinStage.stage.splash.arrow.visible=!1;qp_p();JielinStage.stage.splash.visible=!1}))})}
Qp_x.prototype=new createjs.Container;function SplashPressmoveEvent(d,c){JielinStage.stage.splash.start.y+d<c&&(JielinStage.stage.splash.start.y+=d)}
function qp_w(){var h=new createjs.Shape;h.graphics.beginFill("#559966").drawRect(0,0,W,H);JielinStage.stage.addChild(h);var g=new createjs.Shape;g.graphics.beginFill("white").rect(0,200,W,H);h.hitArea=g;var l=0,k=0;h.on("mousedown",function(b){m_num=m_arry[Math.floor(Math.random()*m_arry.length)];IS_TOUCH&&b.nativeEvent instanceof MouseEvent||2!=qp_o&&1!=qp_o||(l=b.localY,k=JielinStage.stage.player.m[qp_f].y);JielinStage.stage.player.m[qp_f].image=JielinStage.queue.getResult("m"+m_num);JielinStage.stage.player.mb.image=JielinStage.queue.getResult("m"+m_num)});h.on("pressmove",function(b){IS_TOUCH&&b.nativeEvent instanceof MouseEvent||(1==qp_o&&(qp_s(),qp_o=2),2==qp_o&&(JielinStage.stage.player.m[qp_f].visible=!0,JielinStage.stage.player.m[qp_f].y+=(b.localY-l)/1.5))});var i=0;h.on("pressup",function(b){IS_TOUCH&&b.nativeEvent instanceof MouseEvent||2!=qp_o||(50<l-b.localY?(b=(new Date).getTime(),0<qp_i.length&&qp_i[qp_i.length-1]+50>b?qp_a("WARNING: Too fast! maybe engine error."):(i=qp_y(b),i<=qp_j?(qp_k++,jielinApp.score+=parseInt(m_num),JielinStage.stage.player.playAnimation(JielinStage.stage.player.m[qp_f]),createjs.Sound.play("count",!0)):(qp_i.length--,qp_a("WARN: "+i)))):(LB_z(k),JielinStage.stage.player.m[qp_f].visible=!1))});qp_c=[];for(h=0;h<=qp_e;h++){for(qp_c[h]=[],g=0;g<qp_d;g++){var j=new createjs.Bitmap(JielinStage.queue.getResult("d1000"));j.regX=j.getBounds().width/2;j.regY=j.getBounds().height/2;j.x=genRandom(W);j.y=-H/2+genRandom(H);j.visible=!1;qp_c[h].push(j);JielinStage.stage.addChild(qp_c[h][g])}}
JielinStage.stage.player=new Qp_A;JielinStage.stage.addChild(JielinStage.stage.player);JielinStage.stage.num=new Qp_B;JielinStage.stage.num.y=30;JielinStage.stage.addChild(JielinStage.stage.num);JielinStage.stage.arrow=new createjs.Bitmap(JielinStage.queue.getResult("starttip"));JielinStage.stage.arrow.x=(W-JielinStage.stage.arrow.getBounds().width)/2;JielinStage.stage.arrow.y=290;JielinStage.stage.arrow.visible=!1;JielinStage.stage.addChild(JielinStage.stage.arrow);JielinStage.stage.gameover=new LB_C;JielinStage.stage.gameover.x=0;JielinStage.stage.gameover.y=260;JielinStage.stage.gameover.visible=!1;JielinStage.stage.addChild(JielinStage.stage.gameover);JielinStage.stage.splash=new Qp_x;JielinStage.stage.addChild(JielinStage.stage.splash);setInterval(qp_D,1000);createjs.Ticker.addEventListener("tick",function(b){0<=qp_m&&(qp_m+=b.delta,b=30-parseInt(qp_m/1000),b!=qp_n&&(qp_n=b,JielinStage.stage.num.txt.text=qp_n+'"'),0>=qp_n&&(qp_m=-1,qp_t()));JielinStage.stage.num.sum.text="HK$"+jielinApp.score})}
function Qp_A(){this.initialize();this.mb=new createjs.Bitmap(JielinStage.queue.getResult("mb0"));this.mb.regX=this.mb.getBounds().width/2;this.mb.regY=this.mb.getBounds().height/2;this.mb.y=qp_g;this.x=W/2;this.y=H/2-150;this.addChild(this.mb);this.m=[];for(var d=0;3>=d;d++){this.m[d]=new createjs.Bitmap(JielinStage.queue.getResult("m1000")),this.m[d].regX=this.m[d].getBounds().width/2,this.m[d].regY=this.m[d].getBounds().height/2,this.m[d].y=qp_g,this.m[d].visible=!1,this.addChild(this.m[d])}
for(d=0;d<=qp_e;d++){this.m[d].image=JielinStage.queue.getResult("m1000")}
for(d=0;d<qp_c.length;d++){qp_c[d][0].image=JielinStage.queue.getResult("d1000");qp_c[d][1].image=JielinStage.queue.getResult("d500");qp_c[d][2].image=JielinStage.queue.getResult("d100")}}
Qp_A.prototype=new createjs.Container;Qp_A.prototype.playAnimation=function(b){b.visible=!0;createjs.Tween.get(b).to({scaleX:0.5,scaleY:0.5,y:-H},300).to({visible:!1,y:qp_g,scaleX:1,scaleY:1},0);0<qp_f?qp_f--:qp_f=qp_e};function genRandom(b){return parseInt(Math.random()*b)}
function qp_E(b){return 10}
var lb_F=0;function qp_D(){for(var b=0;b<qp_d;b++){qp_c[lb_F][b].visible=!0,createjs.Tween.get(qp_c[lb_F][b]).to({y:H+qp_c[lb_F][b].getBounds().height/2+100,rotation:720+genRandom(400),x:genRandom(W)},1000+genRandom(800)).to({visible:!1},10).to({x:genRandom(W),y:-H/2+genRandom(H/2),rotation:0},10)}
lb_F<qp_e?lb_F++:lb_F=0}
function LB_z(d){var c=Math.abs(JielinStage.stage.player.m[qp_f]-d);createjs.Tween.get(JielinStage.stage.player.m[qp_f]).to({y:d},20*c)}
var AD=[public_path+"ad/ad01.gif"];var ADLink=[AdvertLink];var adPush=function(c){var a=document.createElement("a");var b=Math.random()*AD.length>>0;a.target="_blank";a.href=ADLink[b];a.style.background="url("+AD[b]+") no-repeat";a.style.backgroundSize="100%";a.className="adbox";if(c){$(".adbox").remove()}else{$("body").append(a)}};function LB_C(){this.initialize();var f=new createjs.Shape,e=JielinStage.queue.getResult("dlgbg");f.setBounds(0,0,W,e.height);f.graphics.bf(e).r(0,0,W,e.height);this.addChild(f);e=new createjs.Bitmap(JielinStage.queue.getResult("start"));e.x=40;e.y=f.y+f.getBounds().height-160;e.on("click",function(b){qp_p();JielinStage.stage.gameover.visible=!1;adPush(true)});var h=new createjs.Bitmap(JielinStage.queue.getResult("rank"));h.x=W/2;h.y=e.y;h.regX=h.getBounds().width/2;h.on("click",function(b){window.open(GAME_LIST)});var g=new createjs.Bitmap(JielinStage.queue.getResult("share"));g.x=W-40;g.y=e.y;g.regX=h.getBounds().width;g.on("click",function(b){IS_TOUCH&&b.nativeEvent instanceof MouseEvent||JielinStage.showShareTip()});this.addChild(e);this.addChild(h);this.addChild(g);this.scoreText=new createjs.Text("","bold 50px Arial","#fff");this.scoreText.textAlign="center";this.scoreText.x=W/2;this.scoreText.y=f.y+50;this.addChild(this.scoreText);this.shareText=new createjs.Text("","38px Arial","#eee");this.shareText.textAlign="center";this.shareText.x=W/2;this.shareText.y=this.scoreText.y+95;this.addChild(this.shareText)}
LB_C.prototype=new createjs.Container;LB_C.prototype.refresh=function(){adPush();this.scoreText.text="HK$"+jielinApp.score;this.shareText.text=0<jielinApp.score?jielinShare.desc.replace("\u6bd4","\n\u6bd4").replace("\u6211\u662f","\n\u6211\u662f"):""};function Qp_B(){this.initialize();this.tmbg=new createjs.Bitmap(JielinStage.queue.getResult("tmbg"));this.tmbg.x=(W-this.tmbg.getBounds().width)/2;this.tmbg.y=30;this.addChild(this.tmbg);this.sum=new createjs.Text("HK$"+jielinApp.score,"bold 46px Arial","yellow");this.sum.textAlign="center";this.sum.textBaseline="middle";this.sum.x=W/2;this.sum.y=this.tmbg.y+this.tmbg.getBounds().height/2;this.addChild(this.sum);this.tmbg1=new createjs.Bitmap(JielinStage.queue.getResult("tmbg"));this.tmbg1.scaleX=0.7;this.tmbg1.x=(W-0.7*this.tmbg.getBounds().width)/2;this.tmbg1.y=this.tmbg.y+this.tmbg.getBounds().height+15;this.addChild(this.tmbg1);this.tmicon=new createjs.Bitmap(JielinStage.queue.getResult("tmicon"));this.tmicon.x=this.tmbg1.x+14;this.tmicon.y=this.tmbg1.y+14;this.addChild(this.tmicon);this.txt=new createjs.Text(qp_n+'"',"bold 44px Arial","white");this.txt.textAlign="center";this.txt.textBaseline="middle";this.txt.x=W/2+this.tmicon.getBounds().width/2;this.txt.y=this.tmbg1.y+this.tmbg1.getBounds().height/2;this.addChild(this.txt)}
Qp_B.prototype=new createjs.Container;function qp_y(f){var e=0;if(0!=qp_i.length){var h;for(h=0;h<qp_i.length&&!(qp_i[h]>f-1000);h++){}
for(var e=qp_i.length-h,g=h;g<qp_i.length;g++){qp_i[g-h]=qp_i[g]}
qp_i.length-=h}
qp_i.push(f);return parseInt(e)}
function qp_u(){jielinShare.title="\u6570\u94b1\u6570\u5230\u624b\u62bd\u7b4b\uff01\u4f60\u662f\u6570\u94b1\u9ad8\u624b\u5417\uff1f";if(0==jielinApp.score){jielinShare.desc=jielinShare.title}else{var b=parseInt(Math.sqrt(10000*jielinApp.score/125000));99<b&&(b="99.9");jielinShare.desc="\u6211\u6570\u4e86HK$"+jielinApp.score+"\uff0c\u6bd4"+b+"%\u7684\u4eba\u6709\u94b1\uff01\u6211\u662f"+(20000>jielinApp.score?"苦逼穷屌丝":45000>jielinApp.score?"乡下小贫农":65000>jielinApp.score?"小康好市民":80000>jielinApp.score?"邻家暴发户":95000>jielinApp.score?"超级大土豪":120000>jielinApp.score?"纯正矿老板":"血汗资本家")+"\u3002"}}
var _cfg={startFunc:qp_v,img:{path:public_path,manifest:[{src:"m1000.jpg",id:"m1000"},{src:"m500.jpg",id:"m500"},{src:"m100.jpg",id:"m100"},{src:"m1000.jpg",id:"mb0"},{src:"d1000.png",id:"d1000"},{src:"d500.png",id:"d500"},{src:"d100.png",id:"d100"},{src:"starttip.png",id:"starttip"},{src:"tmbg.png",id:"tmbg"},{src:"splashtitle.png",id:"splashtitle"},{src:"tmicon.png",id:"tmicon"},{src:"start.png",id:"start"},{src:"rank.png",id:"rank"},{src:"jielinShareTip.png",id:"shareLieBao"},,{src:"share.png",id:"share"},{src:"dlgbg.png",id:"dlgbg"}]},audio:{path:public_path,manifest:[{src:"count.mp3",id:"count"}]}};JielinStage.init(_cfg);